package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseShip<M extends BaseBaseShip<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setShipowname(java.lang.String shipowname) {
		set("shipowname", shipowname);
		return (M)this;
	}

	public java.lang.String getShipowname() {
		return get("shipowname");
	}

	public M setShipName(java.lang.String shipName) {
		set("ship_name", shipName);
		return (M)this;
	}

	public java.lang.String getShipName() {
		return get("ship_name");
	}

	public M setPhoneNum(java.lang.String phoneNum) {
		set("phone_num", phoneNum);
		return (M)this;
	}

	public java.lang.String getPhoneNum() {
		return get("phone_num");
	}

	public M setIdNumber(java.lang.String idNumber) {
		set("ID_number", idNumber);
		return (M)this;
	}

	public java.lang.String getIdNumber() {
		return get("ID_number");
	}

	public M setShipTon(java.lang.String shipTon) {
		set("ship_ton", shipTon);
		return (M)this;
	}

	public java.lang.String getShipTon() {
		return get("ship_ton");
	}

	public M setGradeSail(java.lang.String gradeSail) {
		set("grade_sail", gradeSail);
		return (M)this;
	}

	public java.lang.String getGradeSail() {
		return get("grade_sail");
	}

	public M setBusinessRoute(java.lang.String businessRoute) {
		set("business_route", businessRoute);
		return (M)this;
	}

	public java.lang.String getBusinessRoute() {
		return get("business_route");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}

	public java.lang.String getOpenBank() {
		return get("open_bank");
	}

	public M setNameBank(java.lang.String nameBank) {
		set("name_bank", nameBank);
		return (M)this;
	}

	public java.lang.String getNameBank() {
		return get("name_bank");
	}

	public M setCardBank(java.lang.String cardBank) {
		set("card_bank", cardBank);
		return (M)this;
	}

	public java.lang.String getCardBank() {
		return get("card_bank");
	}

	public M setUpdatetimeBank(java.util.Date updatetimeBank) {
		set("updatetime_bank", updatetimeBank);
		return (M)this;
	}

	public java.util.Date getUpdatetimeBank() {
		return get("updatetime_bank");
	}

	public M setVisaSheet(java.lang.String visaSheet) {
		set("visa_sheet", visaSheet);
		return (M)this;
	}

	public java.lang.String getVisaSheet() {
		return get("visa_sheet");
	}

	public M setShipInspection(java.lang.String shipInspection) {
		set("ship_inspection", shipInspection);
		return (M)this;
	}

	public java.lang.String getShipInspection() {
		return get("ship_inspection");
	}

	public M setLoading(java.lang.String loading) {
		set("loading", loading);
		return (M)this;
	}

	public java.lang.String getLoading() {
		return get("loading");
	}

	public M setOperation(java.lang.String operation) {
		set("operation", operation);
		return (M)this;
	}

	public java.lang.String getOperation() {
		return get("operation");
	}

}
