package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseShipCrew<M extends BaseBaseShipCrew<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTBaseShipId(java.lang.Integer tBaseShipId) {
		set("t_base_ship_id", tBaseShipId);
		return (M)this;
	}

	public java.lang.Integer getTBaseShipId() {
		return get("t_base_ship_id");
	}

	public M setCrewName(java.lang.String crewName) {
		set("crew_name", crewName);
		return (M)this;
	}

	public java.lang.String getCrewName() {
		return get("crew_name");
	}

	public M setCrewCertificate(java.lang.String crewCertificate) {
		set("crew_certificate", crewCertificate);
		return (M)this;
	}

	public java.lang.String getCrewCertificate() {
		return get("crew_certificate");
	}

	public M setIdCardCertificate(java.lang.String idCardCertificate) {
		set("ID_card_certificate", idCardCertificate);
		return (M)this;
	}

	public java.lang.String getIdCardCertificate() {
		return get("ID_card_certificate");
	}

}
