package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSettleApply<M extends BaseSettleApply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setApplyDate(java.util.Date applyDate) {
		set("apply_date", applyDate);
		return (M)this;
	}

	public java.util.Date getApplyDate() {
		return get("apply_date");
	}

	public M setDispatcher(java.lang.String dispatcher) {
		set("dispatcher", dispatcher);
		return (M)this;
	}

	public java.lang.String getDispatcher() {
		return get("dispatcher");
	}

	public M setPlanNo(java.lang.String planNo) {
		set("plan_no", planNo);
		return (M)this;
	}

	public java.lang.String getPlanNo() {
		return get("plan_no");
	}

	public M setConsignor(java.lang.String consignor) {
		set("consignor", consignor);
		return (M)this;
	}

	public java.lang.String getConsignor() {
		return get("consignor");
	}

	public M setShipName(java.lang.String shipName) {
		set("ship_name", shipName);
		return (M)this;
	}

	public java.lang.String getShipName() {
		return get("ship_name");
	}

	public M setShipOwnerName(java.lang.String shipOwnerName) {
		set("ship_owner_name", shipOwnerName);
		return (M)this;
	}

	public java.lang.String getShipOwnerName() {
		return get("ship_owner_name");
	}

	public M setShipOwnerPhone(java.lang.String shipOwnerPhone) {
		set("ship_owner_phone", shipOwnerPhone);
		return (M)this;
	}

	public java.lang.String getShipOwnerPhone() {
		return get("ship_owner_phone");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public M setSeagoingVesselName(java.lang.String seagoingVesselName) {
		set("seagoing_vessel_name", seagoingVesselName);
		return (M)this;
	}

	public java.lang.String getSeagoingVesselName() {
		return get("seagoing_vessel_name");
	}

	public M setFreightBeginEnd(java.lang.String freightBeginEnd) {
		set("freight_begin_end", freightBeginEnd);
		return (M)this;
	}

	public java.lang.String getFreightBeginEnd() {
		return get("freight_begin_end");
	}

	public M setLoadingTonnage(java.math.BigDecimal loadingTonnage) {
		set("loading_tonnage", loadingTonnage);
		return (M)this;
	}

	public java.math.BigDecimal getLoadingTonnage() {
		return get("loading_tonnage");
	}

	public M setAdjustFreight(java.math.BigDecimal adjustFreight) {
		set("adjust_freight", adjustFreight);
		return (M)this;
	}

	public java.math.BigDecimal getAdjustFreight() {
		return get("adjust_freight");
	}

	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public M setManagerReview(java.lang.Integer managerReview) {
		set("manager_review", managerReview);
		return (M)this;
	}

	public java.lang.Integer getManagerReview() {
		return get("manager_review");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
