package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDispatchDetail<M extends BaseDispatchDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPlanNoId(java.lang.String planNoId) {
		set("plan_no_id", planNoId);
		return (M)this;
	}

	public java.lang.String getPlanNoId() {
		return get("plan_no_id");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public M setContants(java.lang.String contants) {
		set("contants", contants);
		return (M)this;
	}

	public java.lang.String getContants() {
		return get("contants");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setPlannedQty(java.math.BigDecimal plannedQty) {
		set("planned_qty", plannedQty);
		return (M)this;
	}

	public java.math.BigDecimal getPlannedQty() {
		return get("planned_qty");
	}

	public M setFreightRates(java.math.BigDecimal freightRates) {
		set("freight_rates", freightRates);
		return (M)this;
	}

	public java.math.BigDecimal getFreightRates() {
		return get("freight_rates");
	}

}
