package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDispatch<M extends BaseDispatch<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPlanNo(java.lang.String planNo) {
		set("plan_no", planNo);
		return (M)this;
	}

	public java.lang.String getPlanNo() {
		return get("plan_no");
	}

	public M setExamineState(java.lang.Boolean examineState) {
		set("examine_state", examineState);
		return (M)this;
	}

	public java.lang.Boolean getExamineState() {
		return get("examine_state");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public M setConsignor(java.lang.String consignor) {
		set("consignor", consignor);
		return (M)this;
	}

	public java.lang.String getConsignor() {
		return get("consignor");
	}

	public M setDeliveryDock(java.lang.String deliveryDock) {
		set("delivery_dock", deliveryDock);
		return (M)this;
	}

	public java.lang.String getDeliveryDock() {
		return get("delivery_dock");
	}

	public M setDestinationPort(java.lang.String destinationPort) {
		set("destination_port", destinationPort);
		return (M)this;
	}

	public java.lang.String getDestinationPort() {
		return get("destination_port");
	}

	public M setSeagoingVesselName(java.lang.String seagoingVesselName) {
		set("seagoing_vessel_name", seagoingVesselName);
		return (M)this;
	}

	public java.lang.String getSeagoingVesselName() {
		return get("seagoing_vessel_name");
	}

	public M setSettlePrice(java.lang.String settlePrice) {
		set("settle_price", settlePrice);
		return (M)this;
	}

	public java.lang.String getSettlePrice() {
		return get("settle_price");
	}

	public M setEstimatedArrvialDate(java.util.Date estimatedArrvialDate) {
		set("estimated_arrvial_date", estimatedArrvialDate);
		return (M)this;
	}

	public java.util.Date getEstimatedArrvialDate() {
		return get("estimated_arrvial_date");
	}

	public M setTransportConsumption(java.lang.String transportConsumption) {
		set("transport_consumption", transportConsumption);
		return (M)this;
	}

	public java.lang.String getTransportConsumption() {
		return get("transport_consumption");
	}

	public M setDischargePeriod(java.util.Date dischargePeriod) {
		set("discharge_period", dischargePeriod);
		return (M)this;
	}

	public java.util.Date getDischargePeriod() {
		return get("discharge_period");
	}

	public M setExcessDeductionPrice(java.lang.String excessDeductionPrice) {
		set("Excess_deduction_price", excessDeductionPrice);
		return (M)this;
	}

	public java.lang.String getExcessDeductionPrice() {
		return get("Excess_deduction_price");
	}

	public M setBerthingTonnage(java.math.BigDecimal berthingTonnage) {
		set("berthing_tonnage", berthingTonnage);
		return (M)this;
	}

	public java.math.BigDecimal getBerthingTonnage() {
		return get("berthing_tonnage");
	}

	public M setTotalQuantity(java.math.BigDecimal totalQuantity) {
		set("total_quantity", totalQuantity);
		return (M)this;
	}

	public java.math.BigDecimal getTotalQuantity() {
		return get("total_quantity");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
		return (M)this;
	}

	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

	public M setEntryMan(java.lang.String entryMan) {
		set("entry_man", entryMan);
		return (M)this;
	}

	public java.lang.String getEntryMan() {
		return get("entry_man");
	}

	public M setBilling(java.lang.Boolean billing) {
		set("billing", billing);
		return (M)this;
	}

	public java.lang.Boolean getBilling() {
		return get("billing");
	}

	public M setPortFee(java.lang.Boolean portFee) {
		set("port_fee", portFee);
		return (M)this;
	}

	public java.lang.Boolean getPortFee() {
		return get("port_fee");
	}

	public M setInsurance(java.lang.Boolean insurance) {
		set("insurance", insurance);
		return (M)this;
	}

	public java.lang.Boolean getInsurance() {
		return get("insurance");
	}

}
