package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNoticeWaybill<M extends BaseNoticeWaybill<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setNoticeId(java.lang.Integer noticeId) {
		set("notice_id", noticeId);
		return (M)this;
	}

	public java.lang.Integer getNoticeId() {
		return get("notice_id");
	}

	public M setDispatchShipId(java.lang.Integer dispatchShipId) {
		set("dispatch_ship_id", dispatchShipId);
		return (M)this;
	}

	public java.lang.Integer getDispatchShipId() {
		return get("dispatch_ship_id");
	}

	public M setPlanNo(java.lang.String planNo) {
		set("plan_no", planNo);
		return (M)this;
	}

	public java.lang.String getPlanNo() {
		return get("plan_no");
	}

	public M setFlow(java.lang.String flow) {
		set("flow", flow);
		return (M)this;
	}

	public java.lang.String getFlow() {
		return get("flow");
	}

	public M setShipName(java.lang.String shipName) {
		set("ship_name", shipName);
		return (M)this;
	}

	public java.lang.String getShipName() {
		return get("ship_name");
	}

	public M setShipOwnerName(java.lang.String shipOwnerName) {
		set("ship_owner_name", shipOwnerName);
		return (M)this;
	}

	public java.lang.String getShipOwnerName() {
		return get("ship_owner_name");
	}

	public M setShipOwnerPhone(java.lang.String shipOwnerPhone) {
		set("ship_owner_phone", shipOwnerPhone);
		return (M)this;
	}

	public java.lang.String getShipOwnerPhone() {
		return get("ship_owner_phone");
	}

	public M setPreRefuel(java.math.BigDecimal preRefuel) {
		set("pre_refuel", preRefuel);
		return (M)this;
	}

	public java.math.BigDecimal getPreRefuel() {
		return get("pre_refuel");
	}

	public M setRefuelType(java.lang.String refuelType) {
		set("refuel_type", refuelType);
		return (M)this;
	}

	public java.lang.String getRefuelType() {
		return get("refuel_type");
	}

	public M setPrepay(java.math.BigDecimal prepay) {
		set("prepay", prepay);
		return (M)this;
	}

	public java.math.BigDecimal getPrepay() {
		return get("prepay");
	}

	public M setSiteRefuel(java.math.BigDecimal siteRefuel) {
		set("site_refuel", siteRefuel);
		return (M)this;
	}

	public java.math.BigDecimal getSiteRefuel() {
		return get("site_refuel");
	}

	public M setSitePay(java.math.BigDecimal sitePay) {
		set("site_pay", sitePay);
		return (M)this;
	}

	public java.math.BigDecimal getSitePay() {
		return get("site_pay");
	}

}
