package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasePort<M extends BaseBasePort<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPort(java.lang.String port) {
		set("port", port);
		return (M)this;
	}

	public java.lang.String getPort() {
		return get("port");
	}

	public M setPortCode(java.lang.String portCode) {
		set("port_code", portCode);
		return (M)this;
	}

	public java.lang.String getPortCode() {
		return get("port_code");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
		return (M)this;
	}

	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

	public M setEntryMan(java.lang.String entryMan) {
		set("entry_man", entryMan);
		return (M)this;
	}

	public java.lang.String getEntryMan() {
		return get("entry_man");
	}

}
