package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseShipHistory<M extends BaseBaseShipHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public M setDeliverCompany(java.lang.String deliverCompany) {
		set("deliver_company", deliverCompany);
		return (M)this;
	}

	public java.lang.String getDeliverCompany() {
		return get("deliver_company");
	}

	public M setReceiptCompany(java.lang.String receiptCompany) {
		set("receipt_company", receiptCompany);
		return (M)this;
	}

	public java.lang.String getReceiptCompany() {
		return get("receipt_company");
	}

	public M setLoadingDate(java.util.Date loadingDate) {
		set("loading_date", loadingDate);
		return (M)this;
	}

	public java.util.Date getLoadingDate() {
		return get("loading_date");
	}

	public M setEmptyDate(java.util.Date emptyDate) {
		set("empty_date", emptyDate);
		return (M)this;
	}

	public java.util.Date getEmptyDate() {
		return get("empty_date");
	}

	public M setLossRate(java.math.BigDecimal lossRate) {
		set("loss_rate", lossRate);
		return (M)this;
	}

	public java.math.BigDecimal getLossRate() {
		return get("loss_rate");
	}

	public M setDemurrage(java.math.BigDecimal demurrage) {
		set("demurrage", demurrage);
		return (M)this;
	}

	public java.math.BigDecimal getDemurrage() {
		return get("demurrage");
	}

	public M setPriceFreight(java.math.BigDecimal priceFreight) {
		set("price_freight", priceFreight);
		return (M)this;
	}

	public java.math.BigDecimal getPriceFreight() {
		return get("price_freight");
	}

	public M setCostFreight(java.math.BigDecimal costFreight) {
		set("cost_freight", costFreight);
		return (M)this;
	}

	public java.math.BigDecimal getCostFreight() {
		return get("cost_freight");
	}

}
