package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
		return (M)this;
	}

	public java.lang.String getPublisher() {
		return get("publisher");
	}

	public M setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
		return (M)this;
	}

	public java.lang.String getReceiver() {
		return get("receiver");
	}

	public M setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
		return (M)this;
	}

	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setReview(java.lang.Integer review) {
		set("review", review);
		return (M)this;
	}

	public java.lang.Integer getReview() {
		return get("review");
	}

}
