package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDispatchDetail<M extends BaseDispatchDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPlanNoId(java.lang.Integer planNoId) {
		set("plan_no_id", planNoId);
		return (M)this;
	}

	public java.lang.Integer getPlanNoId() {
		return get("plan_no_id");
	}

	public M setFlow(java.lang.String flow) {
		set("flow", flow);
		return (M)this;
	}

	public java.lang.String getFlow() {
		return get("flow");
	}

	public M setDestinationPort(java.lang.String destinationPort) {
		set("destination_port", destinationPort);
		return (M)this;
	}

	public java.lang.String getDestinationPort() {
		return get("destination_port");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public M setContants(java.lang.String contants) {
		set("contants", contants);
		return (M)this;
	}

	public java.lang.String getContants() {
		return get("contants");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setPlannedQty(java.math.BigDecimal plannedQty) {
		set("planned_qty", plannedQty);
		return (M)this;
	}

	public java.math.BigDecimal getPlannedQty() {
		return get("planned_qty");
	}

	public M setLeftQty(java.math.BigDecimal leftQty) {
		set("left_qty", leftQty);
		return (M)this;
	}

	public java.math.BigDecimal getLeftQty() {
		return get("left_qty");
	}

	public M setFreightRates(java.math.BigDecimal freightRates) {
		set("freight_rates", freightRates);
		return (M)this;
	}

	public java.math.BigDecimal getFreightRates() {
		return get("freight_rates");
	}

	public M setDispatcherEntryTime(java.util.Date dispatcherEntryTime) {
		set("dispatcher_entry_time", dispatcherEntryTime);
		return (M)this;
	}

	public java.util.Date getDispatcherEntryTime() {
		return get("dispatcher_entry_time");
	}

	public M setDispatcher(java.lang.String dispatcher) {
		set("dispatcher", dispatcher);
		return (M)this;
	}

	public java.lang.String getDispatcher() {
		return get("dispatcher");
	}

	public M setSettlePrice(java.math.BigDecimal settlePrice) {
		set("settle_price", settlePrice);
		return (M)this;
	}

	public java.math.BigDecimal getSettlePrice() {
		return get("settle_price");
	}

	public M setGuidePrice(java.math.BigDecimal guidePrice) {
		set("guide_price", guidePrice);
		return (M)this;
	}

	public java.math.BigDecimal getGuidePrice() {
		return get("guide_price");
	}

	public M setFlowState(java.lang.Integer flowState) {
		set("flow_state", flowState);
		return (M)this;
	}

	public java.lang.Integer getFlowState() {
		return get("flow_state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
