package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContract<M extends BaseContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public M setDeliveryDock(java.lang.String deliveryDock) {
		set("delivery_dock", deliveryDock);
		return (M)this;
	}

	public java.lang.String getDeliveryDock() {
		return get("delivery_dock");
	}

	public M setRecipient(java.lang.String recipient) {
		set("recipient", recipient);
		return (M)this;
	}

	public java.lang.String getRecipient() {
		return get("recipient");
	}

	public M setFreightPrice(java.math.BigDecimal freightPrice) {
		set("freight_price", freightPrice);
		return (M)this;
	}

	public java.math.BigDecimal getFreightPrice() {
		return get("freight_price");
	}

	public M setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("delivery_quantity", deliveryQuantity);
		return (M)this;
	}

	public java.math.BigDecimal getDeliveryQuantity() {
		return get("delivery_quantity");
	}

	public M setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
		return (M)this;
	}

	public java.lang.String getAttachment() {
		return get("attachment");
	}

}
