package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNoticeShip<M extends BaseNoticeShip<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setNoticeId(java.lang.Integer noticeId) {
		set("notice_id", noticeId);
		return (M)this;
	}

	public java.lang.Integer getNoticeId() {
		return get("notice_id");
	}

	public M setDispatchDetailId(java.lang.Integer dispatchDetailId) {
		set("dispatch_detail_id", dispatchDetailId);
		return (M)this;
	}

	public java.lang.Integer getDispatchDetailId() {
		return get("dispatch_detail_id");
	}

	public M setDispatchShipId(java.lang.Integer dispatchShipId) {
		set("dispatch_ship_id", dispatchShipId);
		return (M)this;
	}

	public java.lang.Integer getDispatchShipId() {
		return get("dispatch_ship_id");
	}

	public M setShipName(java.lang.String shipName) {
		set("ship_name", shipName);
		return (M)this;
	}

	public java.lang.String getShipName() {
		return get("ship_name");
	}

	public M setShipOwnerName(java.lang.String shipOwnerName) {
		set("ship_owner_name", shipOwnerName);
		return (M)this;
	}

	public java.lang.String getShipOwnerName() {
		return get("ship_owner_name");
	}

	public M setShipOwnerPhone(java.lang.String shipOwnerPhone) {
		set("ship_owner_phone", shipOwnerPhone);
		return (M)this;
	}

	public java.lang.String getShipOwnerPhone() {
		return get("ship_owner_phone");
	}

	public M setIdCardNo(java.lang.String idCardNo) {
		set("id_card_no", idCardNo);
		return (M)this;
	}

	public java.lang.String getIdCardNo() {
		return get("id_card_no");
	}

	public M setLoadingTonnage(java.math.BigDecimal loadingTonnage) {
		set("loading_tonnage", loadingTonnage);
		return (M)this;
	}

	public java.math.BigDecimal getLoadingTonnage() {
		return get("loading_tonnage");
	}

	public M setAvailableTonnage(java.math.BigDecimal availableTonnage) {
		set("available_tonnage", availableTonnage);
		return (M)this;
	}

	public java.math.BigDecimal getAvailableTonnage() {
		return get("available_tonnage");
	}

	public M setArrivalDate(java.util.Date arrivalDate) {
		set("arrival_date", arrivalDate);
		return (M)this;
	}

	public java.util.Date getArrivalDate() {
		return get("arrival_date");
	}

	public M setFreightPrice(java.math.BigDecimal freightPrice) {
		set("freight_price", freightPrice);
		return (M)this;
	}

	public java.math.BigDecimal getFreightPrice() {
		return get("freight_price");
	}

	public M setTotalFreight(java.math.BigDecimal totalFreight) {
		set("total_freight", totalFreight);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFreight() {
		return get("total_freight");
	}

	public M setPrepay(java.math.BigDecimal prepay) {
		set("prepay", prepay);
		return (M)this;
	}

	public java.math.BigDecimal getPrepay() {
		return get("prepay");
	}

	public M setRefuelType(java.lang.String refuelType) {
		set("refuel_type", refuelType);
		return (M)this;
	}

	public java.lang.String getRefuelType() {
		return get("refuel_type");
	}

	public M setPreRefuel(java.math.BigDecimal preRefuel) {
		set("pre_refuel", preRefuel);
		return (M)this;
	}

	public java.math.BigDecimal getPreRefuel() {
		return get("pre_refuel");
	}

	public M setLeftAmount(java.math.BigDecimal leftAmount) {
		set("left_amount", leftAmount);
		return (M)this;
	}

	public java.math.BigDecimal getLeftAmount() {
		return get("left_amount");
	}

	public M setDispatchShipRemark(java.lang.String dispatchShipRemark) {
		set("dispatch_ship_remark", dispatchShipRemark);
		return (M)this;
	}

	public java.lang.String getDispatchShipRemark() {
		return get("dispatch_ship_remark");
	}

	public M setOverGuidePrice(java.lang.Integer overGuidePrice) {
		set("over_guide_price", overGuidePrice);
		return (M)this;
	}

	public java.lang.Integer getOverGuidePrice() {
		return get("over_guide_price");
	}

}
