package yongle.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseGoods<M extends BaseBaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public M setFixedLoss(java.math.BigDecimal fixedLoss) {
		set("fixed_loss", fixedLoss);
		return (M)this;
	}

	public java.math.BigDecimal getFixedLoss() {
		return get("fixed_loss");
	}

	public M setDeductPrice(java.math.BigDecimal deductPrice) {
		set("deduct_price", deductPrice);
		return (M)this;
	}

	public java.math.BigDecimal getDeductPrice() {
		return get("deduct_price");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
		return (M)this;
	}

	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

	public M setEntryMan(java.lang.String entryMan) {
		set("entry_man", entryMan);
		return (M)this;
	}

	public java.lang.String getEntryMan() {
		return get("entry_man");
	}

}
