package yongle.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_button", "id", Button.class);
		arp.addMapping("t_dispatch", "id", Dispatch.class);
		arp.addMapping("t_menu", "id", Menu.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_role_button", "id", RoleButton.class);
		arp.addMapping("t_role_menu", "id", RoleMenu.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

