package yongle.model;

import yongle.model.base.BaseBaseShipCrew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseShipCrew extends BaseBaseShipCrew<BaseShipCrew> {
	public static final BaseShipCrew dao = new BaseShipCrew().dao();
}
