package yongle.model;

import yongle.model.base.BaseBaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseGoods extends BaseBaseGoods<BaseGoods> {
	public static final BaseGoods dao = new BaseGoods().dao();
}
