package yongle.model;

import yongle.model.base.BaseBaseShipHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseShipHistory extends BaseBaseShipHistory<BaseShipHistory> {
	public static final BaseShipHistory dao = new BaseShipHistory().dao();
}
