package yongle.model;

import yongle.model.base.BaseBaseShip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseShip extends BaseBaseShip<BaseShip> {
	public static final BaseShip dao = new BaseShip().dao();
}
