package yongle.model;

import yongle.model.base.BaseBaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseCustomer extends BaseBaseCustomer<BaseCustomer> {
	public static final BaseCustomer dao = new BaseCustomer().dao();
}
