package yongle.model;

import yongle.model.base.BaseBasePort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasePort extends BaseBasePort<BasePort> {
	public static final BasePort dao = new BasePort().dao();
}
