package yongle.model;

import yongle.model.base.BaseButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Button extends BaseButton<Button> {
	public static final Button dao = new Button().dao();
}
