package yongle.model;

import yongle.model.base.BaseCustomerSettle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerSettle extends BaseCustomerSettle<CustomerSettle> {
	public static final CustomerSettle dao = new CustomerSettle().dao();
}
