package yongle.model;

import yongle.model.base.BaseDispatchShip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DispatchShip extends BaseDispatchShip<DispatchShip> {
	public static final DispatchShip dao = new DispatchShip().dao();
}
