package yongle.model;

import yongle.model.base.BaseDispatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dispatch extends BaseDispatch<Dispatch> {
	public static final Dispatch dao = new Dispatch().dao();
}
