package yongle.model;

import yongle.model.base.BaseDispatchDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DispatchDetail extends BaseDispatchDetail<DispatchDetail> {
	public static final DispatchDetail dao = new DispatchDetail().dao();
}
