package yongle.model;

import yongle.model.base.BaseInsidejobContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InsidejobContract extends BaseInsidejobContract<InsidejobContract> {
	public static final InsidejobContract dao = new InsidejobContract().dao();
}
