package yongle.model;

import yongle.model.base.BaseInsidejobContractCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InsidejobContractCopy extends BaseInsidejobContractCopy<InsidejobContractCopy> {
	public static final InsidejobContractCopy dao = new InsidejobContractCopy().dao();
}
