package yongle.model;

import yongle.model.base.BaseNoticeShip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeShip extends BaseNoticeShip<NoticeShip> {
	public static final NoticeShip dao = new NoticeShip().dao();
}
