package yongle.model;

import yongle.model.base.BaseNoticeWaybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeWaybill extends BaseNoticeWaybill<NoticeWaybill> {
	public static final NoticeWaybill dao = new NoticeWaybill().dao();
}
