package yongle.model;

import yongle.model.base.BaseRoleButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleButton extends BaseRoleButton<RoleButton> {
	public static final RoleButton dao = new RoleButton().dao();
}
