package yongle.model;

import yongle.model.base.BaseSettleApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SettleApply extends BaseSettleApply<SettleApply> {
	public static final SettleApply dao = new SettleApply().dao();
}
