package yongle.model;

import yongle.model.base.BaseShipSettle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShipSettle extends BaseShipSettle<ShipSettle> {
	public static final ShipSettle dao = new ShipSettle().dao();
}
