package yongle.model;

import yongle.model.base.BaseStatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statement extends BaseStatement<Statement> {
	public static final Statement dao = new Statement().dao();
}
